### ISSUE TITLE
panic: template index.js:3 function "Name" not defined

### ISSUE THREAD

**Issue by th3fallen** [tmrts/boilr#38]
When attempting to save a local template of the following i get the title'd error

## Command 
`boilr template save templates/feature feature`

## Output
```
panic: template: index.js:3: function "Name" not defined

goroutine 1 [running]:
panic(0x41c800, 0xc42011dde0)
	/home/travis/.gimme/versions/go1.7.linux.amd64/src/runtime/panic.go:500 +0x1a1
text/template.Must(0x0, 0x6a6dc0, 0xc42011dde0, 0x1)
	/home/travis/.gimme/versions/go1.7.linux.amd64/src/text/template/helper.go:23 +0x66
github.com/tmrts/boilr/pkg/template.(*dirTemplate).Execute.func2(0xc420188120, 0x58, 0x6af6e0, 0xc42017ac30, 0x0, 0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/tmrts/boilr/pkg/template/template.go:240 +0x76c
path/filepath.walk(0xc420188120, 0x58, 0x6af6e0, 0xc42017ac30, 0xc420149470, 0x0, 0x0)
	/home/travis/.gimme/versions/go1.7.linux.amd64/src/path/filepath/path.go:351 +0x81
path/filepath.walk(0xc42000bd60, 0x4f, 0x6af6e0, 0xc420115ba0, 0xc420149470, 0x0, 0x1)
	/home/travis/.gimme/versions/go1.7.linux.amd64/src/path/filepath/path.go:376 +0x344
path/filepath.Walk(0xc42000bd60, 0x4f, 0xc420149470, 0x0, 0x0)
	/home/travis/.gimme/versions/go1.7.linux.amd64/src/path/filepath/path.go:398 +0xd5
github.com/tmrts/boilr/pkg/template.(*dirTemplate).Execute(0xc42016a1c0, 0xc42000bbd0, 0x4f, 0xc42016a1c0, 0x0)
	/home/travis/gopath/src/github.com/tmrts/boilr/pkg/template/template.go:254 +0xc1
github.com/tmrts/boilr/pkg/cmd/util.testTemplate(0x7fff5fbff7a4, 0x11, 0x0, 0x0)
	/home/travis/gopath/src/github.com/tmrts/boilr/pkg/cmd/util/validation.go:86 +0x15e
github.com/tmrts/boilr/pkg/cmd/util.ValidateTemplate(0x7fff5fbff7a4, 0x11, 0xc4200abaa0, 0x59926, 0xc420147701)
	/home/travis/gopath/src/github.com/tmrts/boilr/pkg/cmd/util/validation.go:107 +0x27c
github.com/tmrts/boilr/pkg/cmd.MustValidateTemplate(0x7fff5fbff7a4, 0x11)
	/home/travis/gopath/src/github.com/tmrts/boilr/pkg/cmd/must_validate.go:31 +0x41
github.com/tmrts/boilr/pkg/cmd.glob..func7(0x6d4220, 0xc420147740, 0x2, 0x2)
	/home/travis/gopath/src/github.com/tmrts/boilr/pkg/cmd/save.go:31 +0x12f
github.com/spf13/cobra.(*Command).execute(0x6d4220, 0xc4201475a0, 0x2, 0x2, 0x6d4220, 0xc4201475a0)
	/home/travis/gopath/src/github.com/spf13/cobra/command.go:648 +0x443
github.com/spf13/cobra.(*Command).ExecuteC(0x6d3340, 0xc4200abf00, 0x2f, 0xc42011d94a)
	/home/travis/gopath/src/github.com/spf13/cobra/command.go:735 +0x367
github.com/spf13/cobra.(*Command).Execute(0x6d3340, 0xc4200abef8, 0x1)
	/home/travis/gopath/src/github.com/spf13/cobra/command.go:693 +0x2b
github.com/tmrts/boilr/pkg/cmd.Run()
	/home/travis/gopath/src/github.com/tmrts/boilr/pkg/cmd/root.go:52 +0x6c8
main.main()
	/home/travis/gopath/src/github.com/tmrts/boilr/boilr.go:6 +0x14
```

## project.json
```
{
  "Name": "feature"
}
```

## index.js
```
import React, { Component, PropTypes } from 'react';

class {{Name}} extends Component {

  state = {};

  static propTypes = {};

  static defaultProps = {};

  render() {
    return (
      <div></div>
    );
  }
}

export default {{Name}};
```

am i missing something?

**Comment by tmrts** [comment]
Is this the directory tree of `template/feature`?
```tree
feature
├── project.json
└── template
    └── index.js
```

- If not, can you restructure the template and try? 
- If so, can you provide a gist for better inspection?

**Comment by th3fallen** [comment]
doh that did it, my project.json was in the same dir as template. thanks
